### ISSUE TITLE
Make compound split feature optional

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/contextionary#41]
## Reason

The cost is high (almost double the import time in many cases), but the benefits are only high in very specific cases

## Todos

* [x] if `ENABLE_COMPOUND_SPLITTING=true` enable
* [x] else use dummy splitter that does nothing
* [x] make configuration variables only required if enabled==true
